version = 1
SPDX-PackageName = "btp-cloud-identity-services"
SPDX-PackageSupplier = "Valentin Atanassov (valentin.atanassov@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-cloud-identity-services"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-2024 SAP SE or an SAP affiliate company and sap-docs/btp-cloud-identity-services contributors"
SPDX-License-Identifier = "CC-BY-4.0"
